### ISSUE TITLE
官网首页404

### ISSUE THREAD

**Issue by skankhutner42** [786744873/easy-dotnet#1]
<img width="998" alt="Screenshot 2023-09-11 at 11 45 15 AM" src="https://github.com/786744873/easy-dotnet/assets/51079834/9545bb25-5fd7-48f7-8759-5656647687a3">
<img width="998" alt="Screenshot 2023-09-11 at 11 48 28 AM" src="https://github.com/786744873/easy-dotnet/assets/51079834/600f6b36-330a-42a6-b577-12e3081e3fbd">

**Comment by 786744873** [comment]
Thank you for your reminder. This bug has been fixed.🍻
